---
- hosts: localhost
  vars:
      region: "us-east-1"
      instance_type: "t2.micro"
      ami: "ami-08e4e35cccc6189f4"
      keypair: "keerthysith"
      subnetname: ""
      sg_group: "subnet-22451644"
  tasks:
  - ec2:
     key_name: "{{keypair}}"
     image: "{{ami}}"
     region: "{{region}}"
     vpc_subnet_id: "{{subnet-22451644}}"
     wait: yes
     group: "{{sg_group}}"
     count: 1
     count_tag:
            Name: keerthysith
     instance_tags:
              Name: Ansible
    register: ec2
