---
- hosts: localhost
  vars:
      region: "us-east-1"
      instance_type: "t2.micro"
      ami: "ami-08e4e35cccc6189f4"
      keypair: "Jenkins"
      subnetname: "subnet-22451644"
      sg_group: "sg-03d2d864dd279f85b"
  tasks:
  - ec2:
     key_name: "{{keypair}}"
     image: "{{ami}}"
     region: "{{region}}"
     vpc_subnet_id: "{{subnetname}}"
     wait: yes
     group: "{{sg_group}}"
     count: 1
     count_tag:
            Name: instancecount
     instance_tags:
              Name: Ansible
    register: ec2
